import 'package:hive/hive.dart';

/// Represents a spatial coordinate ping collected by the device.
///
/// Contains geographical location details, velocity, heading, and time
/// information suitable for spatial engine processing.
@HiveType(typeId: 0)
class LocationPing extends HiveObject {
  /// The unique hardware or installation identifier of the streaming device.
  @HiveField(0)
  final String deviceId;

  /// The latitude coordinate in decimal degrees.
  @HiveField(1)
  final double latitude;

  /// The longitude coordinate in decimal degrees.
  @HiveField(2)
  final double longitude;

  /// The estimated horizontal accuracy of this position in meters.
  @HiveField(3)
  final double accuracy;

  /// The instantaneous speed of the device in meters per second.
  @HiveField(4)
  final double speed;

  /// The direction of travel in degrees relative to true north (0.0 - 360.0).
  @HiveField(5)
  final double heading;

  /// The Unix timestamp in seconds recorded when the coordinate was captured.
  @HiveField(6)
  final int timestamp;

  /// Indicates whether this coordinate was generated by a mock location provider.
  @HiveField(7)
  final bool isMocked;

  /// Creates a immutable [LocationPing] instance.
  LocationPing({
    required this.deviceId,
    required this.latitude,
    required this.longitude,
    required this.accuracy,
    required this.speed,
    required this.heading,
    required this.timestamp,
    this.isMocked = false,
  });

  /// Converts this [LocationPing] into a JSON-compatible map structure.
  Map<String, dynamic> toJson() => {
        'device_id': deviceId,
        'latitude': latitude,
        'longitude': longitude,
        'accuracy': accuracy,
        'speed': speed,
        'heading': heading,
        'timestamp': timestamp,
        'is_mocked': isMocked,
      };

  /// Constructs a [LocationPing] from a decoded JSON payload map.
  factory LocationPing.fromJson(Map<String, dynamic> json) {
    return LocationPing(
      deviceId: json['device_id'] as String,
      latitude: (json['latitude'] as num).toDouble(),
      longitude: (json['longitude'] as num).toDouble(),
      accuracy: (json['accuracy'] as num).toDouble(),
      speed: (json['speed'] as num).toDouble(),
      heading: (json['heading'] as num).toDouble(),
      timestamp: json['timestamp'] as int,
      isMocked: json['is_mocked'] as bool? ?? false,
    );
  }
}

/// Manual Hive storage adapter for serializing [LocationPing] instances.
class LocationPingAdapter extends TypeAdapter<LocationPing> {
  @override
  final int typeId = 0;

  @override
  LocationPing read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return LocationPing(
      deviceId: fields[0] as String,
      latitude: fields[1] as double,
      longitude: fields[2] as double,
      accuracy: fields[3] as double,
      speed: fields[4] as double,
      heading: fields[5] as double,
      timestamp: fields[6] as int,
      isMocked: fields[7] as bool,
    );
  }

  @override
  void write(BinaryWriter writer, LocationPing obj) {
    writer
      ..writeByte(8)
      ..writeByte(0)
      ..write(obj.deviceId)
      ..writeByte(1)
      ..write(obj.latitude)
      ..writeByte(2)
      ..write(obj.longitude)
      ..writeByte(3)
      ..write(obj.accuracy)
      ..writeByte(4)
      ..write(obj.speed)
      ..writeByte(5)
      ..write(obj.heading)
      ..writeByte(6)
      ..write(obj.timestamp)
      ..writeByte(7)
      ..write(obj.isMocked);
  }
}
